---
- name: Add Vagrant Key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg

- name: Add Vagrant Repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main

- name: Install Vagrant
  apt:
    name: vagrant
    update_cache: yes
